project:
  type: website

exeucte:
  eval: false

website:
  title: "Pablo Science"
  description: "Data Science/AI/Entrepreneurship"
  image: quarto.png
  google-analytics: "G-JJNXYRZ5C4"
  favicon: resources/favicon.png
  open-graph: true
  draft-mode: unlinked

  site-url: https://pavelbaboshkin.github.io/
  repo-url: https://github.com/PavelBaboshkin/pavelbaboshkin.github.io
  # repo-actions: [edit]

  navbar:
    title: false
    background: dark
    pinned: true
    collapse: false
    left:
    - text: "Blog"
      href: index.qmd
    - text: Notes
      file: notes/index.qmd
    - icon: telegram
      href: https://t.me/PavelBaboshkin_channel

  sidebar:
    - title: Notes
      pinned: false
      collapse-level: 1
      style: docked
      contents: notes/

format:
  html:
    reference-location: document
    theme: 
      dark: [solar, resources/custom.scss]
      light: [flatly, resources/custom-light.scss]
    css:
      - resources/styles.css
    toc: true