project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: telegram
        text: Telegram Channel
        href: https://t.me/PavelBaboshkin_channel

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



