project:
  type: website
  output-dir: docs
site:
  favicon: "favicon.png"

website:
  navbar:
    title: false
    pinned: true
    collapse: false
    left:
    - text: Blog
      href: index.qmd
    - text: Notes
      file: notes/index.qmd
    - icon: telegram
      href: https://t.me/PavelBaboshkin_channel
  google-analytics:
    tracking-id: "G-JJNXYRZ5C4"
    anonymize-ip: true


  sidebar:
    - title: Notes
      pinned: false
      collapse-level: 1
      style: docked
      contents: notes/

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css