---
title: Chapter 2. A Theory of Inferred Causation
description: Вводная глава о базовых концепциях
date: "2025-02-24"
categories: [cources]
---

# Базовые идеи

## Фреймворк 

**Причинная структура** - для множества переменных $V$ это направленный ациклический граф в котором ноды соответствуют элементам 
множества $V$ и каждая связь представляет прямую функциональную связь переменных 

**Причинная модель** - это пара $<D, \theta_D>$ состоящая из причинной структуры $D$ и множества параметров $\theta_D$ сопоставимых с
$D$. Параметры $\theta_D$ определяют функции $x_i=\mathcal{F(pa_i, u_i)}$ для каждого $X_i\in V$ и распределение вероятности 
$P(u_i)$ для каждого $u_i$, где $PA_i$ родительская нода $X_i$ в $D$ и $U_i$ случайный шум распределенный согласно $P(u_i)$ независимо от всех остальных $u$

## Выбор моделей 

**Пердполагаемая причинность (предварительная)** - Переменная $X$ влияет на $Y$ если направленный путь существует от $X$ 
к $Y$ в каждой минимальной структуре согласующеся с данными 

**Латентная структура** - это пара $L=<D, O>$ где $D$ это причинная структура на переменных $V$ и $O \in V$ это множество наблюдаемых переменных

**Предпочтение структуры** -  латентная структура $L=<D, O>$ предпочитаема другой $L'=<D', O'>$ ($L \preccurlyeq L'$)
если $D'$ для каждого $\theta_D$ существует $\theta_D'$ такой что $P_[O](<D', \theta_D'>)=P_[O](<D, \theta_D>)$. 
Две структуры эквивалентны если $L \preccurlyeq L'$ и $L' \preccurlyeq L$

**Минимальность** - латентная структура $L$ минимальна для класса структур $\mathcal{L}$ если не существует другого элемента в 
$\mathcal{L}$ который строго предпочитаем $L$

**Консистентность** - латентная структура $L=<D, O>$ сопоставима распределению $\hat{P}$ для переменных $O$ если 
в $D$ есть модели порождающие $\hat{P}$, то есть существует параметризация $\theta_D$ такая что $P_{[O]}(<D, \theta_D>)=\hat{P}$

**Предполагаемая причинность** - при заданной $\hat{P}$ переменная $C$ влияет на $E$ тогда и только тогда если существует прямой путь от 
$C$ к $E$ в каждой минималльной латентной структуре консистентной с $\hat{P}$ 


