---
title: ML Base
description: Освежаем базу
date: "2025-03-07"
categories: [cources]
---

[Ссылка на курс](https://developers.google.com/machine-learning/crash-course)



# ML Models

## Linear regression 

Штуки вида $y=\beta_0 + \beta_1 * x_1 ... + \beta_n * x_n$

Полезное напоминание что MSE тяготеет в выбросам сильнее MAE, вроде очевидно, но вспоминая книжки по causal inference, где куча линейных моделек авторы говорят быть осторожнее с интерпритацией коэффициентов, ибо линии тяготеют к объяснению дисперсии, но будет ли это валидно и для MAE лосса? (вероятно найду ответ на этот вопрос и обновлю эту страницу)


Верно напомнили что SGD это по одному наблюдению, а batch SGD оп группам, НО как часто кто вообще пользуется реально SGD когда говорит о нем, а не подразумевает батчевый? 

У эпохи определение хорошее - в рамках эпохи модель должна увидеть все наблюдения по одному разу

Еще занятна на опросе в конце подловили там был вариант "удвоение learing rate" замедляет обучение, бычно то lr маленькие и увеличение наоборот ускоряет, но в вопросе логика в том, что высокий lr может заставить модель перепрыгивать через минимум - оч валидное замечание для однозначного выпуклого лосса линейных моделей. 

## Logistic regression 

Вдруг кто формулку забыл $y=\frac{1}{1+\exp^{-(\beta_0 + \beta_1 * x_1 ... + \beta_n * x_n)}}$

Оптимизируем LogLoss = $\sum{-y*log(y') - (1-y)*log(1-y')}$

## Classification

Полезное напоминание, что подбор порога это тоже важное занятие

Настолько база, что мне было не лень попросить GPT написать latex для confusion matrix ниже: 
$$
\begin{array}{|c|c|c|}
\hline
& \text{Предсказано положительно} & \text{Предсказано отрицательно} \\
\hline
\text{Фактически положительно} & True Positive & False Negative \\
\hline
\text{Фактически отрицательно} & False Positive & True Negative \\
\hline
\end{array}
$$

Теперь из ячеек складываются метрики: 

* Accuracy - доля правильных ответов = $f \frac{\text{правильные классификации}}{\text{все классификации}}$ = $\frac{TP + TN}{TP + TN + FP + FN}$. Хорошо подходит для грубой и простой оценки качества, стоит использовать только в купе с другими метриками, стоит избегать при сильном дисбалансе классов.  
* Recall (TPR, true positive ratio) - доля правильных положительных ответов среди положительных ответов = $\frac{\text{правильные классификации положительного класса}}{\text{размер положительного класса}}$ = $\frac{TP}{TP + FN}$, интерпретируется как вероятность распознать положительный класс. Полезно смотреть если пропуск наблюдения опаснее ложного результата.
* FPR, false positive ratio - доля неправильных положительных ответов среди негативных ответов = $\frac{\text{неправильные классификации негативного класса}}{\text{размер негативного класса}}$ = $\frac{FP}{FP + TN}$, это вероятность "ложной тревоги". Используем если ложная тревога опаснее пропуска.
* Precision - доля правильных положительных классификаций среди всех положительных классификаций модели = $\frac{\text{положительные предсказания, которые действительно положительные}}{\text{все положительные предсказания}}$ = $\frac{TP}{TP + FP}$ - вероятность того, что модель права, когда предсказывает положительный класс. Используем когда важно, чтобы положительные предсказания действительно были таковыми.
* F1 - гармоническое среднее Precision и Recall = $2*\frac{Precision * Recall}{Precision + Recall}=\frac{2 * TP}{2 * TP + FP + FN}$ - полезна для несбалансированных данных

Receiver-operating characteristic curve (ROC) - кривая для оценки качества модели по всем пороговым значениям, для рисовки говорим, что y = TPR, x = FPR и считаем метрики на каждый возможный порог и рисуем линию, чем ближе она к прямой y=1 тем лучше. Чтобы не смотреть глазами есть метрика AUC - это площадь под ROC кривой, интерпретируется как вероятность для двух наблюдений разного класа отранжировать положительный выше негативного

ROC + AUC хорошо работают для сбалансированных датасетов, для несбалансированных есть другая кривая: Precision - Recall (PRCs) и соответственно площадь под ней, по y - Precision, по x - Recall, значения считаем также для всех порогов 

Так как для обеих кривых значения по осям не больше одного, то максимальная площадь под кривыми = 1, к ней и стремимся 

Подбор порога зависит от целей, но если классы для задачи равнозначны, то валидно считать, что точка на ROC ближайшая к левому верхнему углу - оптимальная и хотим брать её порог. 

Тут забавно ребята стажерский вопрос задали в тесте, внесу и сюда - что делать с моделью, которая предсказывает хуже случайности (AUC < 0.5)

<details>
<summary>Ответ</summary>
Поменять местами классы
</details>

*Смещение предсказаний* - модель должна восстанавливать средние значения распределений с как можно меньшей ошибкой, например если в данных у 5% положительный класс то и у предсказаний должно быть около того. Если это не так, то у модели проблемки, основные причины: 

* Смещения или шум в тренировочнх данных
* Сильная регуляризация 
* Баги :) 
* Фичи не подходят для задачи  

*Многоклассовая классификация* - ситуация когда классов больше двух, ее можно вывести из бинарной если группировать классы по принципу "один vs остальные"

*Мульти-классовая классификация* - ситуация, когда одному объекту могут соответствовать несколько классов

# Data

## Numerical

**Масштабирование** - модель вероятно быстрее обучится и будет честнее оценивать фичи, популярных метода 3: 

* Линейное масштабирование (еще бывает MinMax) - $x'=(x-x_{min})/(x_{max}-x_{min})$, норм если 
    * Размах данные не сильно меняется во времени 
    * Выбросов не много или они не значимы
    * Данные распределены равномерно
* Z-score (обычно и ней говорят в контексте нормализации) - $x'=\frac{x-\mu}{\sigma}/$ - хорошо подходит для около нормальных данных
* Логарифмирование - $x'=ln(x)$ - хороший выбор для степенных распределений 
* Ограничение (cliping) - $x' = \begin{cases}  low & \text{если } x < low \\ x & \text{если } a \leq x \leq b \\ high & \text{если } x > high \end{cases}$ приравниваем все что выше/ниже порога к порогу, полезно для обработки выбросов 

**Группировка** - способ поделить непрерывные данные на группы (бины), норм когда данные кластеризованы (т.е. выделяются группки с определнным значениями). 
Из популярных техник - посмотреть на данные, или поделить по квантилям. 


**Чистка** - с данными надо много работать, почти наверняка в них будут проблемы, самые частые: 

* пропущенные значения 
* дубли 
* аномальные значения 
* ошибки (напрмиер таргет неправльный поставили)

Рекомендации по качественной числовой фиче: 

* понятный нейминг - что меряем, в каких единицах 
* статистический / логический контроль на выбросы 
* выносить скрытые зависимости в отдельные фичи, например вместо заполнения колонки -1, делаем фичу [колонка неопределена]

## Categorical

Прикольное деление по природе категориальных данных: 

* Человеческая разметка - человек вносит ручками. Тут базово считается норм качество, но и люди могут ошибаться, надо контроллировать разные метрики согласованности, например "Cohen's kappa and variants", "Intra-class correlation (ICC)", "Krippendorff's alpha". Из плюсов - отсноительно надежная. Из минусов - дорогая и долгая
* Машинная разметка - другие алгоритмы (обычно речь об ML). Тут качество обычно хуже, но зато быстро и дешево

А я бы еще добавил - автоматическая - это когда классы создаются автоматически по заданным строгим правилам (не вероятностно как в ML). 
Обычно это очень надежная разметка, но супер не гибкая (чтобы добавить класс надо прописать новые правила)

С категориальными данными базово большая беда в размерности - при множестве категориальных фич она быстро разрастается

Хэширование - если категорий слишком много можно их на бакеты поделить и получить категорию поменьше но все еще с информацией

## Data and Generalization


### Характеристики данных 

Норм прикидка размеров данных - данных должно быть на 1-2 порядка больше чем параметров. 

Полезные вопросы для оценки качества датасета: 

* Как много ошибок разметки 
* Как много шума в фичах 
* Как очищенны данные и точно ли это норм

Для пропусков напоминают о важности бинарной фичи вида feature_name_inputed 

### Лейблы

Полезная разбивка типов таргета: 

* прямой - непосредственно отражает цель решаемой задачи 
* прокси - прикидка прямого 

### Дисбаланс

Предлагают в 2 шага побороться с дисбалансом

* downsampling - берем только часть наблюдений по бОльшему классу тем самым немного выравнивая тотал 
* upweighting - назначаем веса выбранным наблюдениям 

Звучит странно - зачем повышать вес у превалирующего класса. Но это нужно, чтобы снизить смещение модели, весдь если в реальных данных соотношение условные 1 к 10_000, то она должна примерно так и предсказывать. А downsampling нужен чтобы модель чаще видела второй класс и не было ситуаций когда на весь батч нет второго класса. 

Еще предлагают эмпирическое правило, что размер батча должен быть хотя бы в пару раз больше величины дисбаланса 

### Генерализация 

Картинка с линиями лосса на трейне и теста - назвается кривой генерализации, вот такой пример приводят

[! A generalization curve that strongly implies overfitting.](https://developers.google.com/static/machine-learning/crash-course/images/RegularizationTwoLossFunctions.png)

Напоминание об идее регуляризации:

* в обычном сценарии модели минимизирует просто лосс $minimize(loss)$
* в регуляризации лосс и какую-то нашу логику оценивающую сложность модели $minimize(loss + complexity)$

Еще лучше мне кажется обозначать слложность как функцию от весов -> $minimize(loss + complexity(w))$

# Advanced ML Models

## Нейронки 


### Backprop

Прикольный чек-лист про проблемы с градиентом: 

* затухающий градиент - когда веса малые, градиент тоже малий и это приводит к медленному обучению - неплхо решается с ReLu 
* "взрывной" градиент - когда веса большие, градиент большой и обучение может ломаться и не сходиться - поможет снижение learning rate 
* отмирание весов - ReLu может сводить параметры в 0, следовательно они больше не участвуют в обучении, но занимают пространство в сетке - поможет снижение learning rate 

### Multi-class

2 основных техники многоклассовой классификации: 

* one-vs-all - проблему классификации на N лкассов воспринимаем как N проблем бинарной классификации и выбираем предикт с наибольшим весом 
* one-vs-one (softmax) - оцениваем вероятности по всем классам сразу 


## Эмбединги

Полезно помнить что они могут быть: 

* статичными - у одной частицы импута эмдеинг всегда одинаковый
* контекстными - эмбединг зависит от 

## LLMs

Мне понравилось объяснение идеи языковой модели: 

* Языковая модель оценивает вероятности встретить следующий токен в зависимости от тех, что уже есть 
* Токен - это составляющая часть той структуры данных, которую хотим прогнозировать, например слово/сочетание/буква, как кирпичик лего 
* Для многих задач важен контекст, поэтому модели выросли в качестве, когда научились его щупать, помогла в этом идея рекурентных блоков