---
title: Summa Technologiae by Stanislaw Lem
description: Прозрение на будущее технологий от одного из самых известных футурологов
date: "2024-07-28"
categories: [books]
---

Сумма технологии для меня была занимательным, но достаточно сложным чтивом. Вики и другие обзоры говорят, что там есть много неточностей в технических моментах, но по-моему главные ценности, которые я извлек для себя, от этого не пострадали, а именно: 

* Книга в наши дни дает возможность сравнить представления о будущем из середины прошлого века с реально наступившим будущим. А значит, можно пробовать искать инварианты.   
* В тексте уделено большое внимание классификациям и всегда полезно посмотреть как другие люди пытались выделять какие-то метки в очень широких понятиях.   
* Лем ставил целью не угадать какие приблуды изобретут в ближайшие 30-100-1000 лет, а рассуждал о том какие пути развития будут продвигаться, поэтому такой подход можно успешно переосмыслить с уточненными за 60 лет с первой публикации знаниями о вселенной.   

По итогу, читать с запросом “разобраться в конкретных технологиях” – скорее не стоит, а для ели “подумать о том, как технологии могут развиваться” – имхо, очень стоящая инвестиция нескольких часов. Из минусов – в том русском переводе, что я читал очень много словесного нагромождения в духе “я конечно сейчас отойду от мысли, но, надеюсь, вы простите эту вольность, ведь иначе мы не сможем увидеть всю картинку, поэтому, приступим рассматривать вопрос…” и т.п. в целом, типичная штука для авторов прошлого века, но пробраться через такой стиль – вполне посильная задача. 

По структуре книга поделена на 8 глав и кучу предисловий и заключений, адресованных переизданиям и локализациям. Я вдумчиво читал первое и последние предисловие и заключение, остальные просматривал, а вот главы хотел бы подробно записать.

**1 – Дилеммы**

Короткая глава, по сути – введение в проблемы, с которыми сталкиваешься в попытках рассуждать о будущем. Отсюда мне понравилось определение технологий “обусловленные состоянием знаний и общественной эффективностью способы достижения целей, поставленных обществом”. Определение столь широко, ведь что бы мы ни делали, мы никогда до конца не знаем что мы делаем. Речь о том, что долгосрочные последствия нам совершенно неизвестны, поэтому в определение технологий необходимо включать контекст времени и его задач. И это первая проблема попыток говорить о будущем – надо знать не только технические моменты, но и угадать цели и задачу будущих исследователей. 

Вторая важная проблема – само мышление человека: 

- Во-первых, мы склонны линейно оценивать нелинейные эффекты. Мы можем достаточно хорошо угадывать что сделать, чтобы технологий стала на 10% лучше, но почти наверняка ошибемся в попытке угадать как сделать её в 1000 раз лучше, поэтому и возникают забавные прогнозы фантастов прошлого.   
- Во-вторых, мы стремимся любое явление рассматривать в рамках замкнутой системы. Нам свойственно все сводить к простым и понятным структурам развития в духе начало-середина-конец, но реальные процессы сложнее и выходят за рамки конечных структур.   


Со знанием этих особенностей проблемы прогноза технологического будущего можно двигаться в более конкретные размышления.

**2 – Две эволюции**

Две эволюции – биологическая и технологическая, идут параллельно, отчасти похожи но имеют разную природу, задачи и законы, но, что значат эти характеристики? Перед рассмотрением сходств и различий надо понять, что как идейно связаны между собой эти две эволюции. Лем использует классификацию Пьера де Латиль из книги “искусственное мышление”, гда различается несколько классов эффекторов (эффектор = орган, способный действовать) : 

* Детерминированные – относительно простые и сопряженные со средой орудия. Это базовые кирпичики и средства для творения обеих эволюций, например молоток для человека или аминокислота для клетки. 
* Организованные эффекторы – системы с обратной связью и самопрограммирующиеся автоматы – компьютеры и люди попадают сюда. 
* Самоизменяемые эффекторы – такие системы, которые могут для достижения своих целей менять самих себя, т.е. они ограничены только строительным материалом, а не стартовыми настройками конкретного состояния системы. Сюда попадает биологический на протяжении его эволюции. 
* Свободный (гипотетический) эффектор – свободен и в выборе “материала строительства”. Некоторые считают, что так развивается наша вселенная, создавая новую материю во время взаимодействия и используя эту материю в новых строениях. 
* “Абсолютный” эффектор – (название это моя вольность, в оригинале это просто теоретически возможная опция) – сам определяет материалы и структуры, т.е. может создавать и использовать строительные материалы не задуманные вселенной. Этого аффектора теолог бы назвал богом, и в книге он упомянут просто для полноты, в анализе он не участвует. 

Собственно к чему это описание? К тому, что оно показывает место и связь двух типов эволюции. 

Биологическая – созданная свободным эффектором (большой взрыв и развитие вселенной) – набрала критическую массу детерминированных эффекторов, которые начали организовываться. Тут некоторые организованные эффекторы (люди) начали создавать искусственные организованные системы.В то же время люди как вид продолжают быть в рамках самоизменяемых эффекторов (т.е. Технологическая эволюция создаваемая организованными эффекторами продолжает зависеть от биологической эволюции. 

Теперь непосредственно к сравнению эволюций: 

В чем эволюции похожи: 

* Сходство динамики развития, сюда попадает:
    - Преемственность развития – все новые виды и технологии стоят на достижениях предыдущих и развивались в обоих видах эволюции похожим образом, от малых прототипов до вполне развитых систем.
    - Одинаковый цикл развития технологии от побочного прототипа до забвения. 
* Изменчивость. Причем и обусловленная требованием выживания и оправданная “сексуальными”, т.е. вкусовыми предпочтениями. 
* Сходство форм – многие решения похожи между типами эволюций и продиктованы ограничениями. 

Как итог сходств приведу цитаты: 

> Мы встречаемся здесь с циклическими процессам, в которых причины становятся следствиями, а следствия – причинами. Процессами, где действуют многочисленные обратные связи, положительные и отрицательные, живые организмы в биологии или последовательно создаваемые промышленностью продукты технической цивилизации являются всего лишь элементарными компонентами этих общих процессов. 
> Вместе с тем такое утверждение проясняет генезис сходства обеих эволюций. И та и другая являются материальными процессами с почти одинаковым числом степеней свободы и близкими динамическими закономерностями. Процессы эти происходят в самоорганизующихся системах, которыми является и вся биосфера земли и совокупность технологических действий человек. А таким системам, как целому, свойственны явления “прогресса”, то есть возрастания эффективности гомеостаза, стремящегося к ультра стабильному равновесию как к своей непосредственной цели.

В чем эволюции различаются: 

* Генезис. Биологическую эволюцию создает природа, технологическую – мы сами.   
* Методология создания. Природа за большое время оттачивала все кирпичики для своих строений путем жесткого отбора наиболее универсальных решенийю Человек же технологиями решает точечные задачи и меняет подходы с малой долей переиспользования. Т.е. Решения природы гораздо универсальнее наших.   
* Отношение теории к практике. В биоэволюции абстрактное знание существует, а мы его активно эксплуатируем.   
* Регулирование. На биологию не влияют мнения, наши же технологии подвержены влиянию общественного и личного мнения.   

**3 – Космические цивилизации**

Вселенная настолько велика, что чисто статистически существование других цивилизаций кажется почти гарантированным, но почему мы их все еще не видим? 

Во-первых, в космосе между объектами огромные расстояния, и мы пока не способны их успешно преодолевать за адекватное по меркам жизни время. Но почему нет других цивилизаций, которые уже развились и ищут собратьев по разумной организации? 

Одна из версий в том, что цивилизации не успешны на длительной дистанции, так, фон Хорнер предлагает 4 причины, почему это происходит: 1) полное уничтожение жизни на планете, 2) уничтожение развитых существ, 3) вырождение психическое или физическое, 4) потеря интереса к науке и технике. Но даже если поставить самые пессимистичные оценки вероятностям этих сценариев, огромный размер вселенной все равно допускает, что должны выжить хотя бы несколько развитых цивилизаций, тогда почему не наблюдаем их? 

Тут полезно уточнить, а что вообще значит “наблюдать”. Есть 3 уровня, как можно доказать наличие другой цивилизации:

1) непосредственный контакт – непрямую увидели/вступили в связь

2) опосредованный контакт – вступили в связь или наблюдаем непосредственно результат деятельности цивилизации 

3) косвенные признаки – “чудеса” – наблюдения, которые могут быть объяснены только инопланетным вмешательством. 

И тут становится ясно, что проблема в нашей методологии. Эффективно перемещаться и искать другие миры мы пока не умеем, поэтому вариант проактивного подтверждения вариантов (1) и (2) – пока отпадает. Вариант, что прилетят к нам – возможен, но от нас не зависит. Остается путь номер три, но его мы сознательно избегаем. Дело в том, что ученые придерживаются принципа бритвы Оккама, и все странности в поведении вселенной будут пытаться объяснить существующими концепциями или концепциями, которые к ним близки. Так, мы скорее придумаем новый класс звезд и будем пытаться его исследовать, чем предположим, что огонек в небе – след от инопланетного корабля. 

Точных объяснений нет, но можно выдвинуть 3 группы гипотез, почему мы наблюдаем “вакуум психозоя”: 

1. Цивилизации возникают в космосе редко, зато являются долговечными, но зависят от возраста галактики. Так, в молодых галактиках еще не прошло достаточно времени, а для анализа старых наша аппаратура еще слишком слаба.     
2. Цивилизации возникают часто, но их жизнь коротка и почти никто не успевает развиться для того, чтобы стать либо заметным, либо научиться искать незаметных.   
3. Цивилизации возникают часто и надолго, но их развитие не похоже на то, как мы его представляем.   

**4 – Интеллектроника**

Все проявления экспоненциального роста ограничиваются средой. Даже искусственные явления зависят от этого, например наука сейчас сталкивается с тем, что рост информации выше чем рост людей её обеспечивающих (ученых), а у ученых пропускная способность ограничена. Это приводит к тому, что в общем виде, кривые развития не экспоненциальные, а S-образные, а варианты улучшения положения надо искать в кибернетике. Одна из максим кибернетики – создание искусственных “мыслящих” систем и с этим связан ряд задач: 

Первая важная задача – контроль распределения знаний, если раньше человек, занятый в производстве продукта знал полный цикл его создания и реализации, то теперь индивидуальное знание ограничено какой-то небольшой зоной, но коллективное знание возросло в разы. Этим свойством надо пользоваться делая доступ к коллективному знанию все проще. (как занимательно он предсказал интернет) 

Другая задача – работа с “черными ящиками”. Так, базовые алгоритмы понятны, их можно разобрать и поместить в памяти, как состояние выходов системы связано с состояниями выходов, но социальные системы, а в будущем и инженерные, уже не будут обладать такими свойствами и надо научиться с этим работать, т.е. придумать как доверять таким ящикам, как контролировать их работу, в каких областях использовать. 

Значимая проблема и мораль кибернетических гомеостатов. Собственно вопросы известные – как и что им позволять определять, вопросы актуальные и ныне. 

Из задачи черных ящиков возникает задача построения их более совершенных прототипов. Так, сейчас LLM решают некоторые задачи очень хорошо и может показаться, что стоит тренировать их на более широкие, регулирующие задачи. Но тут возникает главная проблема такого процесса – надо создавать не регулятор с фиксированными знаниями, а системы регулятора с обратной связью, где баланс между предопределенностью и самоорганизацией – неизвестен, а количество вариантов растет неизвестным темпом в неизвестных направлениях. 

> Табу всегда были направлены в принципе к одной и той же цели: уменьшить хаотическую произвольность индивидуальных действий, уменьшить, свести на нет все это разнообразие – потенциальный источник нарушений равновесия 


Последняя очерченная проблема – как выстроить отношение общества и “черного ящика” по вопросам метафизическим. 

Еще мне понравились рассуждения о связи языка и смыслов. Это натянуто ложится на проблемы “черного ящика”, ибо Лем задается вопросом можно ли решать задачи без сознания, подводя к тому, что машинный перевод без сознания адекватно не выполнить, но время показало иное, поэтому я за утилитарный подход, что качественное решение точной задачи не обязательно решать сознательно. А вот дискуссия насчет языка как явления – занимательная. Так, что считать языком, а что значениями. Например генетический язык, на котором описано яйцо крокодила – сразу и описание явления и явление, но словосочетания на абстрактном языке не становятся явлением. Так, язык это не мышление, а мышление – не язык. Могут существовать бессмысленные фразы, но нет бессмысленных мыслей. Значения не скрыты во фразах, они возникают в уме воспринимающего. 

**5 – Пролегомены к всемогущему**

С какими мыслями столкнется конструктор в попытках все создать? – как-то так я себе описал эту главу. 

Главная концепция, по которой проходят все рассуждения – расположение тех или иных явлений на оси имитология – фантомология. Имитология – создание чего-либо в опоре на найденное в природе. Фантомология – воплощение таких структур, которых в природе еще нет. 

Фантомологии посвящена отдельная глава, а в этой речь идет в основном про имитологию. Так, согласно имитологии, что бы человек ни делал, это моделирование, которое может быть двух видов – модели “существующих явлений”  и модели “несуществующих явлений”. Зачем так сложно? Общий тезис в том, что существующее создала природа, а мы используя выведенное моделями из её знаний, создаем свои новые модели. Формально, несуществующих явлений не должно существовать, т.к. На бесконечности природы возможно все, но законы распределения у этих двух моделирований принципиально разные, поэтому то, что вполне обыденно для нас, в природе может не встретиться и во всей вселенной. 

Так, мы умеем создавать невероятные с точки зрения термодинамики состояния, но, в отличии от природы, не умеем создавать самоорганизуемые масштабные процессы. 

**6 – Фантомология**

Проблема, которую мы будем рассматривать, заключается в следующем: как создать действительность, которая для разумных существ, живущих в ней, ничем не отличалась бы от нормальной действительности, но подчинялась бы другим законом? 

Область знаний для решений этого вопроса назовем фантоматикой. Центральной концепцией, для удобства, будет “фантоматическая машина” – нечто, что создает полную имитацию некоторой реальности с заданными свойствами и нужной нам конструкцией. Собственно над вариантами создания этой машины и бьется фантоматика. Предлагаются 2 вида фантоматики:

Периферическая фантоматика – использует периферические раздражители для воздействия на мозг. Это введение человека в мир ситуаций, нереальность которых обнаружить невозможно. 

Центральная фантоматика – влияет на мозг непосредственно.

Вообще за сложными классификациями и общественными вопросами, скрыто очень простое и точное утверждение: “мы хотим, чтобы нам продавали ощущения”. Ведь ощущения это крутой механизм, выработанный почти совершенным конструктором – природой. А теперь мы можем использовать этот механизм как нам захочется, поэтому теперь создаются и кино, и парки развлечений и VR с нейроинтерфейсами. 

А можно ли подделать наше восприятие ощущений? О чем это – например в VR вы можете получать до 95+% информации о мире, которой располагает акула, но это этого вы не станете думать и чувствовать эту информацию как акула. Зато цереброматика изучает возможности формирования процессов в мозгу, в соответствии с намерениями. Одна из ключевых проблем в этом действие – вопросы личности, например если внушить человеку какой-то технологией не свойственную ему мысль, то будет ли это та же личность? А если нет, то можно ли считать это убийством? Как вариант ответа: 

“Но ведь можно сказать, что жизнь человека от рождения до зрелого возраста представляет собой непрерывное “умирание”, сменяющих друг друга личностей…”

Как быть, если вообще не хотим искусственно влиять на мозг, но новые ощущения создавать хотим? Для  этого есть телетаксия – подключение к машине, которая служит промежуточным звеном между человеком и внешним миром. Так, можно создать двойников, отправить их в разные точки земли и переключаться. 

От телетаксии недалеко до фантопликации, т.е. Подключении нервных путей одного человека к тем же самым нервным путям другого. В такой ситуации тысячи людей смогут одновременно испытывать чей-то опыт. 

Все эти теоретические возможности поднимают кучу вопросов в сфере теории относительности личности, которые сейчас решаются философами, но для претворения в жизнь должны стать точно определенными. 

Все концепции выше были про варианты взаимодействия мира и человеческих ощущений с помощью технологий. Т.е. Мы полагаем, что можем передавать ощущения как информацию, но как тогда вообще связаны личность и информация? Норберт Виннер предположил, что человека можно “передать” по телеграфу, т.е. Однозначно описать всего человека в точке А и воспроизвести точную копию в точке Б. В просто для визуализации варианте этого упражнения – полезно рассмотреть вариации события в духе “в точке А собрали абсолютно точный атомный слепок персоны, а в точке Б его воссоздали”. В таком варианте мы полностью передали всю информацию, но не перенесли и точно не разделили исходную личность, а лишь создали имитации. Поэтому для продолжения существования главный критерий – не информационное сходство, а идентичность генезиса динамической структуры предполагаемого человека. 

**7 – Сотворение миров**

Глава о том, какую роль играет трансценденция в мире и его возможных моделях. 

Если коротко, то есть мнимый уровень – где мы считаем что это трансцендентным только потому, что оно определено вероятностными системами, которые сложно понять. 

Есть абстрактный уровень, где можно допускать теоретическое наличие трансценденции и думать о нем, но на сотворение мира это никак не повлияет. Почему? – Потому что наличие трансценденции претворяется в чудесах, а чудеса не служат подтверждением веры, они преобразуют её в знания, которые стремятся исследовать ученые. Поэтому можно создать одно из двух: либо мир, который знает о своем “трансцендентном” продолжении (а значит и выводит это явление в поле реальности), либо мир, способный верить в трансценденцию, которая то ли существует или нет. 

**8 – Пасквиль на эволюцию**

Если рассматривать эволюцию как конструктора, то он определенно умен, в ситуации явного недостатка ресурсов и высоких требований к изделию добился выдающихся результатов, но есть в них и странности: 

1. Несогласованная избыточность передачи информации. Так, люди регулярно расплачиваются неравномерным старением и генетическими проблемами за недостаточную репликацию важной для строения организма информации.   
2. Не исключение в онтогенезе лишних элементов. Так, в эмбироны людей все еще повторяют стадии свойственные древним эмбриогенезам.   
3. Биохимическая индивидуальность каждой особи. Получается, что помощь других особей извне эволюционно не предусматривалась.    
4. Эволюция плохо работает с долгосрочными изменениями. Так, она не может найти решение, если изменения не становятся полезными “немедленно”, т.е. В первом же поколении. Более того, эволюция плохо справляется с фичами даже в рамках одного поколения, которые проявляются уже вне периода половой активности.   
5. Хатоичность. Эволюция предусмотрела модульность на уровне клеток, но это как плюс так и минус для макро созданий. Удобно, что нам не надо менять руку при небольшом порезе, но плохо, что и сами клетки остаются в воле случайности эволюции.   
6. Отсутствие накопления опыта. Так, многие виды “переизобретали” достижения других. Что вредит как локально – промежуточные особи в уязвленном положении, так и глобально, ведь лучшие решения могут быть разбросаны по разным видам.   

**Послесловие автора**

Чтобы делать не полностью бесплодные заключения о будущем, надо смотреть на самые фундаментальные вопросы текущей науки. 

**Послесловие читателя**

Для меня это была одна из самых сложных книг последнего года, ибо слишком часто заставляет думать в неизвестных направлениях, что, пожалуй и хорошо. Конспект выше оцениваю скорее как удовлетворительный или ниже, но пока не могу найти способа преобразить его в лучшую версию за адекватное время, надеюсь мои заметки хотя бы подстегнули ознакомиться с творчеством Лема.