---
title: The Autobiography of Benjamin Franklin
description: Автобиография одного из самых влиятельных людей в XVIII века
date: "2024-08-12"
categories: [books]
---

Бенджамин Франклин – человек, который сам, с помощью упорной работы и следования своим принципам стал одним из самых влиятельных людей своего века. Его автобиография мне показалась двойственной. С одной стороны, похоже на попытку подробно описать интересные события из своей жизни, а с другой – рефлексия уже очень взрослого человека о том, как и почему он смог прийти к тому, что имеет. 

Вот сторона с анализом причин меня наиболее и заинтересовала. Если коротко, то все дело в том, чтобы быть честным и трудолюбивым, поставить себе цели и неотступно следовать им. Более подробное раскрытие темы приведу в формате выдержек и комментариев. 

> …Зато писание прозы весьма пригодилось мне и помогло продвинуться в жизни

Это скоре контекстная фраза к тому, что Франклин считал навык письма очень важным в жизни. Даже предлагает свою методу его развития – записывать по памяти прочитанные произведения, причем не просто стараясь запоминать, а развивая идеи в том же духе, как это делал автор и пытаясь подбирать лучшие слова и выражения для этого. 

> Когда у человека мало денег, он бывает щедрее, нежели когда имеет их много, – поэтому, возможно, что боится, как бы его не приняли за бедняка.

Для себя так и не решил можно ли однозначно отнести описанное явление к положительному ил инегативному. С одной стороны, логично при низком бюджете активнее сберегать, дабы бюджет рос. Но с другой стороны, в такой ситуации требуется не постепенный, а скачкообразный рост, который возможен при бОльшем риске, а следовательно и тратах. 

> Разум всегда подскажет оправдания для любого поступка, который нам хочется совершить

Посему надо уметь распознавать истинные желания своей личности от мимолетных облегчающих подсказок от разума, которые жертвуют желаемым ради простоты существования.

> Это тоже было одной из серьезных ошибок в моей жизни

Не информативная по тексту фраза, но важная для смысла. Так, Франклин несколько раз указывал на какие-то свои глобальные промахи в работе и отношениях с людьми. Отсюда два главных вывода: как минимум, надо рефлексировать и искать события/действия наиболее нас формирующие, а вообще полезно еще и стараться исправить негативные поступки, сколь бы давними они ни были. 

> 1. Мне необходимо соблюдать крайнюю бережливость – некоторое время, пока я не расплачусь со своими долгами
> 2. Стремиться неизменного говорить правду, ни в коого не вселяя надежд, кои едва ли смогу оправдать, но быть искренним в каждом моем слове и поступке
> 3. Прилежно заниматься любым делом, за какое возьмусь, не отвлекаясь от него легкомысленной погоне за быстрым обогащению, ибо вернейший путь к преуспению лежит через трудолюбие и терпение
> 4. Я обязуюсь ни о ком не отзываться дурно, даже с целью установить истину, но искать оправданий для поступок, в которых обвиняют людей, и пользоваться всяким случаем, чтобы говорить о человеке все то доброе, что я о нем знаю.

То о чем писал в начале, простые принципы, которые надо себе составлять для достижения нового. Конкретно эти были описаны в контексте, когда молодой Франклин вернулся из Лондона в Филадельфию и вступил в новый этап своей жизни.

> Я пришел к убеждению, что главные условия для счастья в жизни – это правдивость, искренность и честность в отношениях между людьми;

Думаю не стоит 1 в 1 принимать чужой вывод об условиях для счастья, но как минимум попробовать сформулировать свои – может быть полезно. 

> … невыгодно называть себя застрельщиком любого полезного начинания, ведь его сразу заподозрят в том, что он ставит себя хоть немножечко да выше людей, его окружающих

Совет из области деловых лайфхаков, которые, как минимум, стоит попробовать. Суть в том, что если надо продать какую-то свою идею представляете её как коллективную, в которой вы лишь представитель. 

> [о пасторе]… он не призывал к соблюдению каких-либо нравственных правил и, казалось, старался сделать нас не достойными гражданами, а всего лишь пресвитерианами.

Кажется это полезно помнить в любой сфере, где один человек выполняет функцию учения для других – религия, преподавание, наставничество и т.п. Главное в таких вопросах – глубинное содержание, а не форма.

Франклин предлагает свою систему по выработке привычек, которые он считал наиболее важными, а именно: Воздержанность, Молчаливость, Аккуратность, Решительность, Бережливость, Трудолюбие, Искренность, Справедливость, Умеренность, Чистоплотность, Спокойствие, Целомудрие, Кротость

Подробнее об этом уже много где хорошо написали, [например](https://vc.ru/u/2230579-kirill-david-razvit-biznes/885986-metod-franklina-sekret-effektivnogo-formirovaniya-privychek)

> Тот, кто один раз оказал тебе услугу, скорее окажет тебе и другую, нежели тот, кому ты сам услужил

Такой психологический эффект даже стал называться [эффектом Бенджамина Франклина](https://ru.wikipedia.org/wiki/%D0%AD%D1%84%D1%84%D0%B5%D0%BA%D1%82_%D0%91%D0%B5%D0%BD%D0%B4%D0%B6%D0%B0%D0%BC%D0%B8%D0%BD%D0%B0_%D0%A4%D1%80%D0%B0%D0%BD%D0%BA%D0%BB%D0%B8%D0%BD%D0%B0#:~:text=%D0%94%D1%80%D1%83%D0%B3%D0%B8%D0%BC%D0%B8%20%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8%2C%20%C2%AB%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82%20%D0%91%D0%B5%D0%BD%D0%B4%D0%B6%D0%B0%D0%BC%D0%B8%D0%BD%D0%B0%20%D0%A4%D1%80%D0%B0%D0%BD%D0%BA%D0%BB%D0%B8%D0%BD%D0%B0,%2C%20%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D1%83%D1%8E%D1%82%D1%81%D1%8F%2C%20%D0%B8%20%D0%BF%D0%B5%D1%80%D0%B5%D1%82%D0%BE%D0%BB%D0%BA%D0%BE%D0%B2%D1%8B%D0%B2%D0%B0%D1%8E%D1%82%D1%81%D1%8F%C2%BB.). Забавно, что у него есть и обратный, когда мы начинаем ненавидеть того, кому причинили зло, дабы оправдать в своих глазах этот поступок. 

> Советую вам в первую очередь обратиться к тем, в чьей поддержке вы уверены; потом к тем, в которых вы сомневаетесь дадут ли они что-нибудь или нет, и показывайте им список тех, кто уже что-то дал; и, наконец, не пренебрегайте и теми, от которых никаких не ждете поддержки ибо в отношении некоторых из них вы могли ошибаться.

Чисто гайд по фандрайзу. 

Штош, “время-деньги” освоена, чтиво занимательное, на 100 долларов мимоходом не попасть.