---
id: cv
title: Pavel Baboshkin
---

## Summary

Увлекаюсь продвинутым анализом данных и ищу в нем вдохновение для решения бизнес задач, называю это Product science. Успешно занимаюсь этим уже 5 лет и уверен что дальше больше) 

## Work Experience

### Magnit Tech
**Team Lead Data Analyst - Strategic Reserch**  
*Sept. 2024 - Present*

- Построил систему верхнеуровневой отчетности мобильного приложения, которая используется многими командами и репортится для C-level
- Провел значимые исследования, которые повлияли на работу с CVM и привлечением аудитории в приложение
- Управлял командой из 3 человек, включая сбор и распределение задач, ревью итогов, развитие сотрудников

### VkusVill
**Senior Data Analyst - Communications**  
*Oct. 2023 - Aug. 2024*

- Провел цикл исследований поведения аудитории в котором доказал ряд идей легших в основу направления онбординга новичков
- Предложил и реализовал MVP баннерных рекомендации на основе многоруких бандитов, по итогу ключевая метрика теста выросла на 5% и решение взяли в продуктовую разработку
- Создал систему отчетности продукта коммуникаций
- Провел 10+ AB полного цикла от формирования гипотез до анализа результата и рекомендаций

### Raiffesien Bank 
**Data Analyst - Data Platform**  
*Jan. 2022 - Sept. 2023*

- Создал руководство по разработке отчетов, что ускорило разработку PBI отчетов на 20%
- Разработал методику оценки BI отчетности, для KPI продуктовых команд.
- Настроил 3 системы отчетности для 1000+ пользователей из доменов: HR, Data, Management

### FA & Thomson Reuters
**Research Analyst - Financial Markets**  
*Sept. 2020 - Dec. 2022*

- Ускорил EDA на 40%
- Создал систему контроля качества данных
- Опубликовал 3 статьи в Q1-Q2

## Personal Projects

- *Winter 2024* [LeadFinder](https://t.me/FindMeLeads_bot) - Создал tg бот для поиска клиентов в телеграм
- *Autumn 2023 - Present* Веду блог об аналитике и IT проектах - [телеграм](https://t.me/PavelBaboshkin_channel), [сайт](https://pavelbaboshkin.github.io/)
- *Winter 2023* KazTech – Создал BI платформу с предиктивной аналитикой грузоперевозок KZ
- *Summer 2021* Largo – Написал TG бот для аналитики портфеля, в пике 1к пользователей MAU

## Education

### НИУ ВШЭ
**ФКН: Магистр по наукам о данных**  
*2023 - 2025*

- ВКР - Анализ CJM пользователя для оптимизации мобильных приложений
- GPA 9.1/10

### London School of Economics
**Экономика и финансы**  
*2019 - 2023*  

- Основной трек - финансовая математика, исследовательский проект - анализ маркетмейкеров на криптовалютном рынке  
- GPA 4.3/5  

### Финансовый университет при Правительстве РФ
**Финтех**  
*2019 - 2023*  

- ВКР в форме стартапа, проект - прогнозная аналитика продаж на маркетплейсах  
- GPA 94.2/100  

## Skills
- SQL - clickhouse, greenplum
- Python - sklearn, pytorch, catboost, pandas, numpy 
- Data Analysis - user event stream analysis, user segmentation, AB testing, causal inference
- Reporting - PowerBI, Yandex Data Lens
