---
title: ML Base
description: Освежаем базу
date: "2025-03-07"
categories: [cources]
---

[Ссылка на курс](https://developers.google.com/machine-learning/crash-course)



# ML Models

## Linear regression 

Штуки вида $y=\beta_0 + \beta_1 * x_1 ... + \beta_n * x_n$

Полезное напоминание что MSE тяготеет в выбросам сильнее MAE, вроде очевидно, но вспоминая книжки по causal inference, где куча линейных моделек авторы говорят быть осторожнее с интерпритацией коэффициентов, ибо линии тяготеют к объяснению дисперсии, но будет ли это валидно и для MAE лосса? (вероятно найду ответ на этот вопрос и обновлю эту страницу)


Верно напомнили что SGD это по одному наблюдению, а batch SGD оп группам, НО как часто кто вообще пользуется реально SGD когда говорит о нем, а не подразумевает батчевый? 

У эпохи определение хорошее - в рамках эпохи модель должна увидеть все наблюдения по одному разу

Еще занятна на опросе в конце подловили там был вариант "удвоение learing rate" замедляет обучение, бычно то lr маленькие и увеличение наоборот ускоряет, но в вопросе логика в том, что высокий lr может заставить модель перепрыгивать через минимум - оч валидное замечание для однозначного выпуклого лосса линейных моделей. 

## Logistic regression 

Вдруг кто формулку забыл $y=\frac{1}{1+\exp^{-(\beta_0 + \beta_1 * x_1 ... + \beta_n * x_n)}}$

Оптимизируем LogLoss = $\sum{-y*log(y') - (1-y)*log(1-y')}$

## Classification

Полезное напоминание, что подбор порога это тоже важное занятие

Настолько база, что мне было не лен попросить GPT написать latex для confusion matrix ниже: 
$$
\begin{array}{|c|c|c|}
\hline
& \text{Предсказано положительно} & \text{Предсказано отрицательно} \\
\hline
\text{Фактически положительно} & True Positive & False Negative \\
\hline
\text{Фактически отрицательно} & False Positive & True Negative \\
\hline
\end{array}
$$

Теперь из ячеек складываются метрики: 

* Accuracy - доля правильных ответов = $f \frac{\text{правильные классификации}}{\text{все классификации}}$ = $\frac{TP + TN}{TP + TN + FP + FN}$. Хорошо подходит для грубой и простой оценки качества, стоит использовать только в купе с другими метриками, стоит избегать при сильном дисбалансе классов.  
* Recall (TPR, true positive ratio) - доля правильных положительных ответов среди положительных ответов = $\frac{\text{правильные классификации положительного класса}}{\text{размер положительного класса}}$ = $\frac{TP}{TP + FN}$, интерпретируется как вероятность распознать положительный класс. Полезно смотреть если пропуск наблюдения опаснее ложного результата.
* FPR, false positive ratio - доля неправильных положительных ответов среди негативных ответов = $\frac{\text{неправильные классификации негативного класса}}{\text{размер негативного класса}}$ = $\frac{FP}{FP + TN}$, это вероятность "ложной тревоги". Используем если ложная тревога опаснее пропуска.
* Precision - доля правильных положительных классификаций среди всех положительных классификаций модели = $\frac{\text{положительные предсказания, которые действительно положительные}}{\text{все положительные предсказания}}$ = $\frac{TP}{TP + FP}$ - вероятность того, что модель права, когда предсказывает положительный класс. Используем когда важно, чтобы положительные предсказания действительно были таковыми.
* F1 - гармоническое среднее Precision и Recall = $2*\frac{Precision * Recall}{Precision + Recall}=\frac{2 * TP}{2 * TP + FP + FN}$ - полезна для несбалансированных данных

Receiver-operating characteristic curve (ROC) - кривая для оценки качества модели по всем пороговым значениям, для рисовки говорим, что y = TPR, x = FPR и считаем метрики на каждый возможный порог и рисуем линию, чем ближе она к прямой y=1 тем лучше. Чтобы не смотреть глазами есть метрика AUC - это площадь под ROC кривой, интерпретируется как вероятность для двух наблюдений разного класа отранжировать положительный выше негативного

ROC + AUC хорошо работают для сбалансированных датасетов, для несбалансированных есть другая кривая: Precision - Recall (PRCs) и соответственно площадь под ней, по y - Precision, по x - Recall, значения считаем также для всех порогов 

Так как для обеих кривых значения по осям не больше одного, то максимальная площадь под кривыми = 1, к ней и стремимся 

Подбор порога зависит от целей, но если классы для задачи равнозначны, то валидно считать, что точка на ROC ближайшая к левому верхнему углу - оптимальная и хотим брать её порог. 

Тут забавно ребята стажерский вопрос задали в тесте, внесу и сюда - что делать с моделью, которая предсказывает хуже случайности (AUC < 0.5)

<details>
<summary>Ответ</summary>
Поменять местами классы
</details>

*Смещение предсказаний* - модель должна восстанавливать средние значения распределений с как можно меньшей ошибкой, например если в данных у 5% положительный класс то и у предсказаний должно быть около того. Если это не так, то у модели проблемки, основные причины: 

* Смещения или шум в тренировочнх данных
* Сильная регуляризация 
* Баги :) 
* Фичи не подходят для задачи  

*Многоклассовая классификация* - ситуация когда классов больше двух, ее можно вывести из бинарной если группировать классы по принципу "один vs остальные"

*Мульти-классовая классификация* - ситуация, когда одному объекту могут соответствовать несколько классов

# Data