---
title: Chapter 2. A Theory of Inferred Causation
description: Теория предполаагемый следствий
date: "2025-02-24"
categories: [cources]
---

# Базовые идеи

## Фреймворк 

**Причинная структура** - для множества переменных $V$ это направленный ациклический граф в котором ноды соответствуют элементам 
множества $V$ и каждая связь представляет прямую функциональную связь переменных 

**Причинная модель** - это пара $<D, \theta_D>$ состоящая из причинной структуры $D$ и множества параметров $\theta_D$ сопоставимых с
$D$. Параметры $\theta_D$ определяют функции $x_i=\mathcal{F(pa_i, u_i)}$ для каждого $X_i\in V$ и распределение вероятности 
$P(u_i)$ для каждого $u_i$, где $PA_i$ родительская нода $X_i$ в $D$ и $U_i$ случайный шум распределенный согласно $P(u_i)$ независимо от всех остальных $u$

## Выбор моделей 

**Пердполагаемая причинность (предварительная)** - Переменная $X$ влияет на $Y$ если направленный путь существует от $X$ 
к $Y$ в каждой минимальной структуре согласующеся с данными 

**Латентная структура** - это пара $L=<D, O>$ где $D$ это причинная структура на переменных $V$ и $O \in V$ это множество наблюдаемых переменных

**Предпочтение структуры** -  латентная структура $L=<D, O>$ предпочитаема другой $L'=<D', O'>$ ($L \preccurlyeq L'$)
если $D'$ для каждого $\theta_D$ существует $\theta_D'$ такой что $P_[O](<D', \theta_D'>)=P_[O](<D, \theta_D>)$. 
Две структуры эквивалентны если $L \preccurlyeq L'$ и $L' \preccurlyeq L$

**Минимальность** - латентная структура $L$ минимальна для класса структур $\mathcal{L}$ если не существует другого элемента в 
$\mathcal{L}$ который строго предпочитаем $L$

**Консистентность** - латентная структура $L=<D, O>$ сопоставима распределению $\hat{P}$ для переменных $O$ если 
в $D$ есть модели порождающие $\hat{P}$, то есть существует параметризация $\theta_D$ такая что $P_{[O]}(<D, \theta_D>)=\hat{P}$

**Предполагаемая причинность** - при заданной $\hat{P}$ переменная $C$ влияет на $E$ тогда и только тогда если существует прямой путь от 
$C$ к $E$ в каждой минималльной латентной структуре консистентной с $\hat{P}$ 

## Стабильность распределений

**Стабильность** - пусть $I(P)$ это условно независимые связи которые есть в $P$. Тогда причинная модель $M=<D, \theta_D>$, описывает
стабильное распределение если $P(<D, \theta_D>)$ не содержит посторонних независимостей, то есть для любых параметров $\theta_D'$ выполняется $I(P(<D, \theta_D)>)\in I(P(<D, \theta_D'))$. Это значит, что варьируя параметрами от $\theta$ к $\theta'$ мы не теряем информацию о независимости в $P$. 

Классная аналогия, пусть есть картинка на которой мы видим стул и надо выбрать между 2 теориями:  
1) На картинке стул  
2) На картинке или стул или 2 стула, расположенных так, что один закрывает другой     

Эта задача решается принципами минимальности и стабильности вот так:  
- минимальность - 1 предпочитетельнее 2 потому что множество ситуаций типа 1 это подмножество ситуаций типа 2, поэтому пока не будет доказательств в пользу обратного, стоит выбирать 1  
- стабильность - маловероятно, чтобы один объект так перекрывал другой, потому что даже небольшой сдвиг второго стула делал бы его заметным, поэтому теория 1 более стабильна к изменениям окружающей среды     
  
## Выяснение структур

**Индуктивная причинность**
Input: $\hat{P}$ устойчивое распределение на множестве переменных $V$  
Алгоритм:  
1) Для каждой пары переменных a, b из множества V, ищем множество $S_ab$ такое, что a и b независимы при фиксации $S_ab$. Создаем ненаправленный граф G такой, что вершины a, b соеденены только если множество $S_ab$ не находится   
2) Для каждой пары несмежных переменных a,b c общим соседом c проверяем $c \in S_ab$:   
- если да идем на шаг 3   
- если нет, добавляем стрелки, указывающие на c например $a-> c <- b$  
3) В частично направленном графе рекурсивно размечаем как можно больше стрелок удовлетворяя двум условиям:  
- любая альтернативная ориентация приведет к новой v структуре  
- любая альтенативная ориентация создаст направленный цикл  
Output: паттерн $H(\hat{P}$ сопоставимый с $\hat{P}$

**Индуктивная причинность со скрытыми переменными**
Input: $\hat{P}$ устойчивое распределение и допускаются скрытые структуры 
Алгоритм:  
1) Для каждой пары переменных a, b ищем множество $S_ab$ такое, что a и b независимы при фиксации $S_ab$. Если такое множество не находится создаем ненаправленное ребро  
2) Для каждой пары несмежных переменных a,b c общим соседом c проверяем $c \in S_ab$:   
- если да идем на шаг 3   
- если нет, добавляем стрелки, указывающие на c например $a-> c <- b$  
1) В частично направленном графе рекурсивно размечаем как можно больше стрелок удовлетворяя двум правилам:  
- для каждой пары не соседних a и b c общим соседом c если существует направление $a->c$ и нет направления $b->c$ то добавляем направление $c->b$ 
- если a,b соседние и существует направленный путь из a в b то размечаем направленность из a в b  
Output: основной паттерн $\hat{P}$ 

**Потенциальная причина** - Переменная $X$ потенциально влияет на $Y$ если:   

* $X$ и $Y$ зависимы в любом срезе (контексте)   
* Существует переменная $Z$ и контекст $S$ такие что:
    + $X$ и $Z$ независимы при заданном $S$, т.е. $X \perp Z | S$  
    + $Z$ и $Y$ независимы при заданном $S$, т.е. $Z \not\perp Y | S$

Где контекст это множество переменных с зафиксированными значениями 


**Действительная причина** - $X$ действительно влияет на $Y$ если существует такая переменная $Z$ что: 

* $X$ и $Y$ зависимы в любом контексте и существует контекст $S$ который удовлетворяет следующему: 
    + $Z$ это потенциальная причина $X$
    + $Z \not\perp Y | S$
    + $Z\perp Y|S \cup X$
* $X$ и $Y$ находятся в транзитивном отношении замыкания 

**Ложная ассоциация** - две переменные $X, Y$ находятся в ложной ассоциации если они зависимы в некотором контексте и существуют 
две переменные $Z_1, Z_2$ и два контекста $S_1, S_2$ такие что 

* $Z_1 \not\perp X | S_1$
* $Z_1 \perp Y | S_1$
* $Z_2 \not\perp Y | S_2$
* $Z_2 \perp X | S_2$

С учетом опрделений выше такое возможно только в структуре $Z_1 \rightarrow X \rightarrow Y \leftarrow Z_2$ 

Логично вспомнить что обычно у нас есть промежуточная информация, следовательно по правилу потенциальной причины можно упростить определения с учетом временной информации.

