---
title: Agent of Influence by Janson Hanson
description: Успешный успех на принципах спецслужб
date: "2024-08-04"
categories: [books]
---

Книга в классическом американском стиле популярной нон фикшн литературы – уйма простых примеров успешного успеха, и короткие итоги после каждого. В таком формате конспектом является сама книга и переписывать я её точно не планировал. Поэтому вот концепции и фразы, которые мне захотелось запомнить: 

Все формы отношений – модификации сделки купли продажи, в бизнесе продают товар или услугу за деньги, в разведке продают секреты за какие-то блага, в любви продают отношение за ощущения. 

**Цикл SADR** – самая эффективная техника продаж:
* Идентификация – надо хорошо разобраться в ситуации: что у нас есть сейчас, чего нет, какая цель и как использовать ресурсы для её достижения.   
* Анализ – оценка реальной ситуации, чтобы определить конкретный план действий. В плоскости общения тут речь о том, чтобы уже из общения выяснить особенности человека, его мотивацию и т.п.   
* Разработка – укрепление связей. Полагается, что на этапе анализа узнали мотивацию всех нужных людей и теперь надо постепенно сближать отношения так, чтобы они приняли от нас помощь с решением их проблемы, в обмен на нужные услуги.   
* Вербовка – презентуем предложение. Главное – делать упор на сопроводительные характеристики сделки, т.е. личные отношения, сервис, и т.п., а техническое качество мы должны были доказать ранее.   

Дополнительный этап – перевод к другому агенту. Речь о том, что один человек не может сопровождать все сделки, особенно это важно для бизнеса, который переходит с малого в средний и основатель начинает делегировать продажи на менеджеров. Тут главное донести, что контакт от этого не станет хуже и менеджеры все сделают в лучшем виде, а для контроля ввести health-чеки, т.к. Регулярные масштабируемые контакты с клиентом, чтобы проверить все ли в порядке и показать, что отношения все еще крепки. 

**Рефлекс уверенности** – то, что дает возможность справиться со всем – непоколебимая внутренняя вера в себя, в свою способность немедленно ринуться в бой или найти правильное решение, невзирая на обстоятельства. Для развития рефлекса полезно: 

* Хорошо понимать конечный результат при постановке цели   
* Отслеживать прогресс, ежедневно фиксировать все подробности наблюдений и действий   
* Следовать плану и доводить дела до конца   
* Забить на мнение окружающих, быть уверенным в правильности своих действий  
* Развивать самоуважение через честность, принципиальность, трудолюбие   
* Заботиться о здоровье   

**Метод песочных часов** – способ разговорить человека – начинаете диалог с широкой темы, постепенно сужаете до интересуемой конкретики, затем снова выводите в широкую. Идея в том, что люди запоминают начало и конец диалога, и мы делаем их безобидными, а середину используем в своих целях.
