---
title: Data for the People by Andreas Wiegend
description: Немного страшилок, немного предложений по теме упраления данными людей
date: "2024-07-23"
categories: [books]
---

Книгу я читал на русском в исполнении издательства Бомбора, что может добавлять свое искажение. Например, неясно как появилось название “BIG DATA вся технология в одной книге” из оригинального “DATA FOR THE PEOPLE how to make our post-privacy economy work for you”. Но, все-таки, ожидаю, что проблемы перевода не коснулись основных идей книги. 

В книге 7 глав, но можно их идейно поделить на 2 блока: первый – в классическом американском стиле с кучей примеров показывает, что от анализа наших данных компаниями никуда не скрыться; второй – набор предложений автора по тому, как компаниям и людям надо с этими данными работать. Свои мысли по этим блокам и опишу ниже.

## Блок первый – как компании работают с данными сейчас

Тут почти все крутилось вокруг оси из этих 4 идей:

1. Компании собирают о нас все данные, какие только могут. А большие компании делают это давно и успешно.   
2. Из накопленных данных компании знают о нас много, вероятно сильно больше, чем мы предполагаем, что о нас знают. А еще это позволяет компаниям прогнозировать наше поведение.   
3. Люди почти почти не умеют определять точные причины и природу своих мыслей и действий.   
4. лагодаря возможности компаний из пункта 2 и особенностям людей из пункта 3 – компании могут не просто прогнозировать наше поведение, но и формировать его. А это может недружелюбно не безопасно, и вообще плохо, поэтому во второй части книги будет раскрытие как с этим быть.   

Кажется, что идея из 4 шагов выше могла бы занимать меньше чем ~150 страниц, но это не повод для критики, тем более, что там было несколько занимательных рассуждений:

Во-первых, мне понравилась краткая история приватности от Андреаса Вайгенда: 

* В деревенской жизни частной жизни не существовало. Физически невозможно что-либо надежно скрывать, когда живешь все время в одном помещении с десятком родичей.   
* Камины позволили делать жилища более сложными (больше комнат и этажей), что дает людям возможность хотя бы в рамках личных комнат отстраивать какую-то частную жизнь.   
* Тайное голосование и четвертая поправка принесли приватность в политику  
* В конце 19 века начали узаконивать право на неприкосновенность частной жизни, сделав приватность юридически законной.   
* В наши дни интернет делает частную жизнь иллюзий, и нам самим нравится делиться информацией о себе (забавно это писать в личном блоге)   

Во-вторых, на многих примерах хорошо разбит миф, что компании пристально следят за каждым. Часто этот тезис фигурирует в духе “я с друзьями обсудил, что классно дома иметь гриль, а не следующий день везде рекламируется крутой гриль, значит гугл за мной следит”. Нет, это значит, что гугл хорошо насобирал данные, которые ты сам предоставил (фотки, поисковые запросы, покупки и т.п.), а затем гугл заметил, что еще 100 тысяч похожих на тебя мужичков, которые выкладывали фотки с шашлыков вскоре хотели купить себе гриль, а значит и ты вероятно захочешь, поэтому держи рекламу. 

В-третьих, многим известно, но от того не менее важно. Гений крупных интернет компаний в том, что они построили такую цепочку, где пользователю выгодно сообщать информацию о себе, а затем эту цепочку масштабировали на большую аудиторию, этим ходом завладели огромным ресурсов человеческого внимания, а затем это внимание научились конвертировать в деньги. 

## Блок второй – как компаниям стоит работать с данными ради пользователей

На протяжении всей книги, но особенно сильно с пятой главы Андреас предлагает свое видение путей решения проблем предоставления и использования личных данных компаниям и государству.  Идейно. Проблемы того, как организовать контроль за личными данными – вопросы важные, но мне показались очень странными предложенные варианты решения, поэтому вот авторская структура предложений в этой сфере и мои пояснения о чем каждый пункт, чтобы дальше обсуждать:

Для людей должны реализовываться два права, способствующие повышению прозрачности обработки данных: 

1) Право на доступ к своей информации – люди должны знать как используются любые, связанные с ними, данные. бОльшая претензия сейчас к тому, что социальные данные активно используются везде, от e-com, до банков, но человек об этом использовании ничего не знает. 

2) Право на инспекцию обработчиков данных, включающее: 

* Право на ознакомление с аудитом сохранности данных   
* Право на ознакомление с коэффициентом использования частной информации   
* Право на ознакомление с показателем доходности информационных активов   
В целом эти о том, что человек должен знать как используются его данные и достаточно ли он получает от этого использования. 

Четыре права, способствующие расширению свободы выбора для пользователей:

* Право вносить исправления в информацию – аналог права на свободу самовыражения, в том плане, что надо иметь возможность менять любую информацию о себе, даже если не вы её автор.   
* Право на размытие данных о себе – должна быть возможность выбора насколько точной информацией хотим делиться, например координатаму с точностью в метр или квартал или город.    
* Право экспериментировать с обработкой данных – пользователь должен иметь возможность самостоятельно менять веса в алгоритмах, которые работают в используемых сервисах.   
* Право переносить свои данные – пользователь должен без потери накопленных данных о себе суметь перейти от одной компании к другой без потери качества алгоритмов.   

## Критика

Во-первых, странное позиционирование важности этих проблем для пользователей. Для половины аргументом было, что-то в духе “разве не удобно ли пользователям самим это настраивать”. Если коротко, то нет, не просто так сервисы от огромных сложных фильтров приходят к базовым + рекомендациям. К тому же, в первой части выяснили, что у людей плохо с самопознанием, поэтому цель того, чтобы каждый мог регулировать всеми параметрами модели рекомендаций для него – мне неясна. К тому же, это по сути и происходит само собой, когда люди взаимодействуют с продуктом, так, как сами хотят, именно это взаимодействие и адаптирует алгоритм под каждого пользователя без необходимости самостоятельно определять веса всех моделей. (а во времена нейронок с миллиардами весов, эта возможность вообще забавно выглядит) 

Во-вторых, слишком мало рассуждений о том, зачем эти меры компаниям? Списывать все на то, что раз может быть нужно некоторым пользователям, значит надо законодательно такие нормы вводить – слишком наивно. Так-то государства самый крупный владелец информационной асимметрии, и из предложенных инициатив неясно в чем win-win для сборщиков данных. У меня наоборот каждый раз были размышления, о том, как эти меры будут вредить бизнесу, например, идея переносимости данных убивает программы лояльности, а право полного контроля за экспериментами делает повторение любых алгоритмов в 100 раз дешевле, а следовательно невыгодно инвестировать в их первичное дорогое создание. 

В-третьих – может это и не было целью, но для меня странно, что предлагается куча разнообразных идей, но почти не рассматривается их реализация. Как надо реализовывать аудит сохранности данных, как считать возвратность инвестиций информации, какие есть роли в этих процессах и т.п. Конечно, почти всегда приводится образный очерк примерной реализации, но нигде этот очерк не выдерживает и первого неудобного вопроса. Например, для расчета коэффициента доходности информационных активов предлагается делить затраты пользователя по сбору и предоставлению информации на доходность от этой информации. Так пользователь сможет получать обоснованную чиселку стоимости его данных и будет понимать стоит ли передача этих данных этой компании того или нет. Но зачем такой сложный механизм, если он автоматически заложен в концепцию рынка. Если человек считает, что он не получит достаточно ценности от ВК, то он не пойдет регистрироваться там. Если человек считает, что время на заполнение стартовой формы не стоит ценности платформы, то он не станет регистрироваться, а если какие-то данные из этой формы не нужны компании, то она вскоре сама это найдет и уберет их или проиграет борьбу конкурентам. 

## Итоги

По первой части, где описывается AS-IS концепция сбора данных о пользователях – если не знакомы с этим, то может быть занимательно, мне было скорее скучно. 

По второй части, где предлагаются идеи по улучшению мира через работу с персональными данными – ситуация, как у безуспешного стартапера, который верит в свой продукт. Есть набор инициатив, но неясно является ли это реальной проблемой, непонятно кто и почему должен этим заниматься и нет значимой конкретики что с этим всем делать. 