---
title: How to see George Nelson
description: Инструкция по тому, как видеть мир
date: "2024-08-15"
categories: [books]
---

Хоть я и не знаю как тут целостно что-либо записать в духе конспекта, но от книги я в восторге. Брал бумажную версию в хорошем варианте и внимательно рассматривал все иллюстрации – очень занимательно и дает пищу для воображения. Для себя хочу записать 2 типа вещей из прочитанного: размышления на тему визуального восприятия и структуру, в которой Нельсон предлагает развивать это восприятие, начну по порядку. 

> … видеть – значит думать. Думать – значит составлять воедино и приводить в порядок случайные частички индивидуального опыта. Видение – не уникальный божественный дар, а учебная дисциплина. Это значит, ему можно научиться. – Джошуа Тейлор

В целом тут речь о том, что людям сейчас недостает способности “видеть”, но это поправимо. Под способностью видеть предполагается навык считывать не только очевидную информацию, но и дополнительные сигналы. Хорошей ассоциацией будет Шерлок Холмс – он в простых вещах видит гораздо больше чем другие люди. 

Дополнительно Нельсон винит индустриализацию в том, что для этой эпохи нужны люди выполняющие функции, а это приводит 

> Мы видим то, с чем подходим к акту видения
> Видите вы ровно то, что думаете.

Самое короткое и крышесносное, что выделил для себя. В каждый момент времени, в любом акте восприятия информации мы обрабатываем новую информацию подходами, которые появились от уже обработанной. И каждая новая дельта информации улучшает наш механизм обработки -> восприятие любого, даже самого стандартизованного примера зависит от от контекста обработчика.  

> …компания безумного творца куда предпочтительнее компании психически здорового критика

Критики характеризуют новое стандартами старого, что никогда не приведет к прорыву. Безумцы, хоть и с низкой конверсий в успех, но творят будущее. 

> Стиль – это видимое выражение сущности и функциональности вещи

> Дизайн – прежде всего процесс: он начинается с потребности или проблемы, а в итоге получается дизайн вещи. Основные правила достаточно просты: спроектированная вещь должна выполнять свою основную функцию

> Дизайн – не украшение, а неотъемлемое выражение функциональности объекта

В таком определении любая деятельность и есть дизайн, и в этом что-то есть. 

Теперь заметки по структуре книги (aka пути тому, как учиться видеть): 
**Коммуникация:**
- Шрифты – форма символа может нести не меньше смысла чем его назначение.   
- Цифры – концентрация информации в простой системе, на даже для них нужны развитые приемники.   
- Фокус внимания – в многомерном мире движение по одной из любых осей раскрывает одну и ту же систему по-разному.   
- Стрелки – следствие стремления к движению и указаниям, мы считываем их подсознательно и даже не понимаем как это важно.   
- Невербальные сообщения – любой объект в любом участке пространства, можно считать невербальным сообщением, уловить и расшифровать   которое может достаточно приближенный к нему приемник.   
- Неформальные сообщения – бунт против невербальных сообщений.    
- Большие надписи – броские формы заметнее их истинного содержания.   
- Важные документы – все, что отдает важностью тяготеет к старине, потому что прошлое мертво и не преподносит сюрпризов.   
- Двойные сообщения – формальные иллюстрации к содержательной информации сплошь и рядом.   
- Запреты – дизайн большинства вещей – запретительный.   
- 
**Искусство:** 
- Портреты – мы всегда изображаем что-либо важное, чем бы оно ни было.   
- Герой, дракон, дама – частый паттерн, пожалуй, во всем.   
- Благородные звери – на животных часто переносится символический смысл  
- Люди и не-люди в пространстве – все чаще человеческий род осмысляют через гуманоидные сравнения   
- Люди-символы – чаще чем животные становятся символами сами люди или выдуманные персонажи   
- Киборги – соединение того, что хорошо знаем (люди), с тем, о чем можем пока только мечтать (роботы)   
- Городские стены – настенная живопись – клапан для выплескивания разочарования, накопленного от жизни  в ухудшающейся среде  
- Повторные взгляды – берем значимую характеристику объекта и переносим её в другой контекст  
- Превращение – как меняется ценность объекта при изменении его характеристик?   
- Стробоскоп – восприятие движения это сравнение статических картинок.   
**Старье:**
- Часы – наблюдать за часами, значит чувствовать учащающийся пульс жизни общества   
- Пожарные гидранты – максимальный утилитаризм в разнообразных формах   
- Деревянные украшения – “в характере нации, которая так много времени и энергии тратит на вырезание узоров из досок, обязательно есть хороший черты”  
- Промышленная романтика – т.к. коммуникации бизнеса односторонние, то от убеждения они перешли к манипуляциям с желаниями людей.   
**Движение:**
- Движение – передвижения делятся на 2 категории: места, где движение плавное и беспрепятственное – уютное, а там, где есть пробки и скачки – некомфортные.  
- Пешеходные улицы – какие выражения лиц на этой улице? Какая мебель и антураж стоят на этой улице? Почти наверняка они будут взаимосвязаны.   
- Сидение – уличное сидение это бесплатный и занимательный досуг Корпоративное сидение, регламентировано и направлено против человека, с целью заражения его посредственностью и скукой.   
- Мостовые – одни из немногих свободных поверхностей в наших городах.   
- Канализационные люки – максимально функциональное решение  
- Сокращение пешеходных зон – есть явная атака в виде прямого сокращение, а также неявная – реклама, авто и вспомогательные постройки все чаще занимают территорию людей   
- Мосты – в отличие от дороги или ВПП, посты совершает прыжок – и воображение прыгает вместе с ним.   
**Геометрия и прочие упражнения:**
- Спирали – они везде, и не всегда понятно почему.   
- Круги – круг это центр всего, символ завершенности, целостности.  
- Узоры – они и динамичны и статичны и нам почему-то нравится их рассматривать.   
- Мягкое и твердое – ищите вокруг мягкое и твердое и отмечайте контрасты между этими двумя свойствами. (зубы и губы, флаг и здание, дирижабль и корзина)   
- Следы – это отметки некоторой истории.   
**Город:**
- Перекрестки – как он обустроен?   
- Горизонты – набор контуров и форм или нагромождение прямоугольников?   
- Реклама – доводит до баннерной слепоты   
- Большие пространства – мы любим большие объемы, где движение уютное.   
- Прерывистость – непрерывные композиции из отдельных элементов   
- Визуальные помехи – фокус на целевой картине не должен прерываться заграждениями.   
- Вид сверху – по верхнеуровневый картинке можно многое прочитать.   
- Рукотворное на фоне природы – человек беспомощен, но интеллект стремится к архитектуре величиной с природу.   
- Прозрачность – способ увидеть или представить мир зазеркалья.  
**Дизайн для выживания:**
- Удачный дизайн – если что-то выглядит так, словно оно и должно делать задуманное, а лучшй дизайн, обычно у вещей, необходимых для выживания – доспехи, спорт  
**Стандартизация/разнообразие/эволюция:**
- Стандартизация – основная проблема в том, что взаимодействий стало так много, что надо снижать число степеней свободы. Так при производстве надо управлять двумя процессами – на выходе поток стандартных продуктов, на выходе – вклад стандартных людей.   
- Идеальный дизайн – зонты, велосипеды, ножницы – стары, функциональны, понятны.   
- Смена форм – дизайн всех элементов следует от выступающих элементов к закрытым формам.   
- Лица – они везде, их надо лишь увидеть.   
- Кокэси – простота развивает мышление и дает волю чувствам.   
- Кнопки – кнопка совершенно нейтральна, она лишь ждет касания пальца. Кнопки привели к пропасти между легкостью усилия для нажатия и масштабом последствий.   
- Хлеб – исток любой цивилизации.  

И что в итоге? Я не знаю как написать вывод к такому и нужен ли он тут вообще. Мне понравилось, медиа сопровождение текста – чудесное, а дальше каждый должен *увидеть* нечто сам для себя. 