---
title: The Road to Serfdom by Friedrich Hayek
description: Эссе о политике и экономике от левого крыла середины XX века
date: "2024-08-08"
categories: [books]
---

Обзоров в интернете хватает, мне кажется вполне достаточным посмотреть эти 3 документа по теме: [вики](https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D1%80%D0%BE%D0%B3%D0%B0_%D0%BA_%D1%80%D0%B0%D0%B1%D1%81%D1%82%D0%B2%D1%83), [комикс от журнала Look](https://cdn.mises.org/Road%20to%20Serfdom%20in%20Cartoons.pdf), [политический блог](https://ancapchan.info/2020/01/02/3443/). Для особо упорных еще может быть интересно посмотреть рецензии в онлайн магазинах книг, особенно занимательные там полярные мнения от ярых либералов или социалистов, как, например, [тут](https://www.livelib.ru/review/3504700-doroga-k-rabstvu-fridrih-avgust-fon-hajek#comments). 

Для своего же конспекта просто хочу зафиксировать фразы автора и свои мысли к ним:

> … может быть, наиболее значительным последствием всех этих достижений  следует считать совершенно новое ощущение власти человека над своей судьбой и убеждение в неограниченности возможностей совершенствования условий жизни. Успехи рождали новые устремления, а по мере того, как многообещающие перспективы становились повседневной реальностью, человек хотел двигаться вперед все быстрее.

Соглашусь, что ощутимое влияние усилий на улучшение благосостояния – отличный стимул для развития, но не уверен, что он может одинаково эффективно работать на всей человеческой выборке, посему и в либеральных формах взаимодействия возникают способы организации и упорядочения человеческой жизни. 

> Демократия утверждает высочайшую ценность каждого человека, социализм превращает человека в простое средство, в цифру. Демократия и социализм не имеют между собой ничего общего кроме одного слова: равенство. Но посмотрите, какая разница: если демократия стремится к равенству в свободе, то социализм – к равенству в рабстве и принуждении – де Токвиль. 

Тут надо оговориться, что вся соль в контексте, так, социализм сводится к рабству из-за того, что регуляторные функции там контролируются, а это потом начинает определять всю жизнь от работы до развлечений. Так вот, идея кажется слишком идеализированной, ведь в демократии равенство свободы при прочих равных факторах труда, а в социализме напрямую в труде, проблема в том, кто, как и почему будет определять этот труд. 

> Планирование и конкуренция соединимы лишь на пути планирования во имя конкуренции, но не на пути планирования против конкуренции

Опять оговорка – планирование тут это не просто прогноз для повышения прозрачности работы, а регуляторное планирование, т.е. Определение некоторого плана и требование его полного выполнения обществом. Тут прикол в том, что никакой социалист демона Лапласа не раздобудет, следовательно не сумеет спрогнозировать все потребности, что могут возникнуть в обществе, следовательно его план всегда будет ограничивающим. 

> … но нельзя отрицать возможности путем принудительной стандартизации или запрета разнообразия достигать в некоторых областях изобилия, способного возместить отсутствие выбора. Можно даже предположить, что когда-нибудь будет сделано такое изобретение, которое принесет огромную выгоду обществу, но лишь при условии, если им будут одновременно пользоваться все или почти все

Классическая история о том, что есть сферы или ситуации, когда контроль повышает локальную эффективность решения, но  к этому простой контраргумент и опять со стороны планирования – раз контроллер не может знать глобальные оптимальные опции, то риск того, что принуждение близкой удачной опции вытеснит естественный путь становления еще более удачной – велик.  

> Иллюзия специалистов, что плановое общество будет уделять больше сил достижению целей, которые его волнуют, – явление, допускающее и более широкое истолкование. Ведь все мы в чем-то заинтересованы, что-то предпочитаем и в этом смысле подобны специалисту. И мы наивно думаем, что наша личная иерархия ценностей имеет значение не только для нас и что в свободной дискуссии с разумными людьми мы сможем убедить их в справедливости наших воззрений.

Суровая правда, об интересах индивида печется только индивид, harmful but true.

> Если в момент принятия закона известен его результат, такой закон уже не может являться инструментом, который свободный человек может использовать по своему усмотрению. Это инструмент, с помощью которого законодатель воздействует на людей, преследуя свои цели.

Какой-то парадоксальный вывод, ведь принимать закон, не зная какие могут быть последствия – шиза, но прогнозировать последствия = рушить индивидуализм. Где-то по соседству в тексте Хаек описывать, что так-то законы могут быть, главное чтобы только о защите свободы и выполнении свободных контрактов пеклись, но как принимать хотя бы такие законы, не предполагая, к чему они будут приводить? Короче, приведенный тезис отношу к очень спорным, ведь законы, по-хорошему, должны быть системой для реализации общественной цели и развиваться с учетом обратной связи. Например хотим. Чтобы люди не воровали свободу других, придумываем как это можно описать в нпа, потом видим, что все пользуются лазейкой и цель не выполнена, адаптируем текст нпа и так по кругу. 

> Человек свободен, если он должен подчиняться не другому человеку, но закону – Кант

Звучит разумно. Можно разгонять в духе, а будет ли транзитивной связь создание закона – подчинение, т.е. логично ли сказать, что при подчинении закону мы на какую-то часть подчиняемся воле его создателя, если да, то как это чинить? 

> Было бы правильнее видеть  в деньгах величайший из когда-либо изобретенных человеком инструментов свободны. Именно деньги открывают теперь перед бедными гораздо большие возможности, чем несколько поколений назад были открыты перед богатыми

Деньги и деньги, че бубнеть то. А если серьезно, то я скорее не понимаю описание оппозиции  – челов, которые “ненавидят деньги, усматривая в них символ этих ограничений, налагаемый нашей относительной бедностью”. Во-первых, насколько это не преувеличение и настолько ярые и значимые критики денег существуют. Во-вторых, обе позиции странные, деньги просто инструмент, удобный способ договариваться о чем-либо. 

> Планирование затронет не только наши те маргинальные нужды, которые мы обычно имеем в виду, говоря о “чистой экономике”. Дело в том, что нам как индивида мне будет позволено судить, что является для нас второстепенным.

Ну собственно еще один пример того, что планирование не может учитывать разносторонние потребности, следовательно ни серого, ни, тем более, черного секторов экономики не будет, а доступные опции будут ограничены и проранжированы по социальной одобряемости.

> Когда людей лишают возможности свободно путешествовать, покупать иностранные журналы и книги, когда контакты с заграницей могут осуществляться только по инициативе или с одобрения официальных инстанций общественное мнение оказывается под гораздо более жестким контролем, чем были при любом абсолютистском режиме

А как быть если ограничение вроде как внешнее, но там не все так однозначно… 

> Те, кто в главном отказываются от свободы во имя временной безопасности, не заслуживают ни свободы ни безопасности – Б. Франклин.

Согл. 

> Всякая власть развращает, но абсолютная власть развращает абсолютно – Лорд Актон. 

Попосовые эксперименты по типу [Тюремный эксперимент в Стэнфорде](https://www.imdb.com/title/tt0420293/) чуть ли не убеждают, что это то, как наш мозг устроен. 

> Между тем непонятно, почему система должна обладать теми же достоинствами, что и побуждения, которые привели к её созданию

Просто напоминание о том, что анализ результатов деятельности должен быть вне контекста автора деятельности, чтобы не пытаться приписать в какую-либо из сторон оценочные суждения. 

> … самую многочисленную ценностно однородную группу составляют люди, моральный уровень которых невысок

По собственному опыту сказать пока ничего не могу, но как мысль на подумать – занимательная. В целом, если мораль может быть проксирована каким-то образованием или чем-то в этом духе, то звучит логично, что чем выше развитость этого прокси, тем больше вариантов этого развития, тем разнообразнее индивиды.

> Современный человек все чаще склонен считать себя моральным, потому что он переносит свои пороки на все более и более обширные группы – Р. Нибур.

Психология толпы, все дела. Занимательно, что актуальность проблемы все растет, т.к. сейчас порог входа во все новые группы ниже чем когда-либо. 

> Одной из лучших гарантий мира станет такой международный орган, который будет ограничить власть государства над личностью.

А кто будет ограничивать власть этого органа по контролю власти государства над личностью?